default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: classified_development

test:
  <<: *default
  database: classified_test

production:
  <<: *default
  database: classified_production
  username: classified
  password: <%= ENV['CLASSIFIED_DATABASE_PASSWORD'] %>
